version: 2

project_name: csctl

before:
  hooks:
    - go mod download

builds:
  - id: csctl
    main: ./cmd/csctl
    binary: csctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Exclude Windows ARM64 (limited support)
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: csctl
    builds:
      - csctl
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 1
    - title: Security
      regexp: "^.*sec[(\\w)]*:.*$"
      order: 2
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:.*$"
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: CraftedSignal
    name: cli
  prerelease: auto
  draft: false
  name_template: "v{{ .Version }}"
