version: 2

project_name: csctl

before:
  hooks:
    - go mod download

builds:
  - id: csctl
    main: ./cmd/csctl
    binary: csctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Exclude Windows ARM64 (limited support)
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: csctl
    ids:
      - csctl
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

dockers_v2:
  - images:
      - "ghcr.io/craftedsignal/csctl"
    tags:
      - "v{{ .Version }}"
      - "latest"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
    dockerfile: .github/Dockerfile
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "CraftedSignal CLI for detection-as-code"
      "org.opencontainers.image.url": "https://github.com/CraftedSignal/cli"
      "org.opencontainers.image.source": "https://github.com/CraftedSignal/cli"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.licenses": "MIT"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 1
    - title: Security
      regexp: "^.*sec[(\\w)]*:.*$"
      order: 2
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:.*$"
      order: 3
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: CraftedSignal
    name: cli
  prerelease: auto
  draft: false
  name_template: "v{{ .Version }}"
