package yaml

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/craftedsignal/cli/pkg/schema"
	"gopkg.in/yaml.v3"
)

// LoadedRule represents a rule loaded from a file.
type LoadedRule struct {
	Rule     schema.Detection
	FilePath string
	Hash     string
}

// LoadAll loads all YAML files from a directory recursively.
func LoadAll(root string) ([]LoadedRule, error) {
	var rules []LoadedRule

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		ext := strings.ToLower(filepath.Ext(path))
		if ext != ".yaml" && ext != ".yml" {
			return nil
		}

		loaded, err := LoadFile(path, root)
		if err != nil {
			return fmt.Errorf("failed to load %s: %w", path, err)
		}

		rules = append(rules, loaded...)
		return nil
	})

	return rules, err
}

// LoadFile loads rules from a single YAML file.
func LoadFile(path, root string) ([]LoadedRule, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	// Calculate relative path for folder-based groups
	relPath, _ := filepath.Rel(root, path)
	folderGroups := extractFolderGroups(relPath)

	// Try to parse as single document first
	var single schema.Detection
	if err := yaml.Unmarshal(data, &single); err == nil && single.Title != "" {
		// Merge folder groups with explicit groups
		single.Groups = mergeGroups(folderGroups, single.Groups)

		return []LoadedRule{{
			Rule:     single,
			FilePath: path,
			Hash:     ComputeHash(single),
		}}, nil
	}

	// Try as array
	var multiple []schema.Detection
	if err := yaml.Unmarshal(data, &multiple); err == nil {
		var rules []LoadedRule
		for _, r := range multiple {
			r.Groups = mergeGroups(folderGroups, r.Groups)
			rules = append(rules, LoadedRule{
				Rule:     r,
				FilePath: path,
				Hash:     ComputeHash(r),
			})
		}
		return rules, nil
	}

	return nil, fmt.Errorf("invalid YAML format")
}

// SaveFile saves a rule to a YAML file.
func SaveFile(rule schema.Detection, path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	data, err := yaml.Marshal(rule)
	if err != nil {
		return err
	}

	header := fmt.Sprintf("# %s\n# Generated by CraftedSignal\n\n", rule.Title)
	return os.WriteFile(path, append([]byte(header), data...), 0644)
}

func extractFolderGroups(relPath string) []string {
	dir := filepath.Dir(relPath)
	if dir == "." {
		return nil
	}

	parts := strings.Split(dir, string(filepath.Separator))
	var groups []string
	for _, p := range parts {
		if p != "" && p != "." {
			groups = append(groups, p)
		}
	}
	return groups
}

func mergeGroups(folder, explicit []string) []string {
	seen := make(map[string]bool)
	var result []string

	for _, g := range folder {
		if !seen[g] {
			seen[g] = true
			result = append(result, g)
		}
	}
	for _, g := range explicit {
		if !seen[g] {
			seen[g] = true
			result = append(result, g)
		}
	}

	return result
}

// ComputeHash computes a hash of the detection's sync-relevant fields.
func ComputeHash(r schema.Detection) string {
	data := fmt.Sprintf("%s|%s|%s|%s|%s|%s|%s|%s|%v|%v|%v",
		r.Title, r.Description, r.Platform, r.Query, r.Severity, r.Kind,
		r.Frequency, r.Period, r.Tactics, r.Techniques, r.Tags)
	hash := sha256.Sum256([]byte(data))
	return hex.EncodeToString(hash[:])
}
